services:
  - type: web
    name: rangla-punjab-society
    env: node
    plan: free
    buildCommand: |
      cd Frontend && npm install && npm run build
      cd ../Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
